import {
  ArrowRight,
  ArrowUpDown,
  AtSign,
  Archive,
  Bell,
  BriefcaseBusiness,
  Braces,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  CloudUpload,
  Cloud,
  Code2,
  Cpu,
  DatabaseZap,
  FileImage,
  FileText,
  Filter,
  Globe2,
  GripVertical,
  Image,
  ExternalLink,
  LayoutDashboard,
  Lock,
  LoaderCircle,
  LogOut,
  MapPin,
  MessageCircle,
  MoreVertical,
  Moon,
  Paperclip,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  RotateCw,
  SquarePen,
  Download,
  Edit3,
  FolderOpen,
  HardDriveUpload,
  Plus,
  Rocket,
  Search,
  Settings,
  Eye,
  EyeOff,
  FileCode2,
  Github,
  Menu,
  Mail,
  MailCheck,
  Save,
  Star,
  Sun,
  TriangleAlert,
  Trash2,
  TrendingUp,
  UserCircle,
  Wrench,
  X,
  ZoomIn,
  ArrowLeft,
  Send,
  Server,
  Terminal,
  Linkedin,
  Boxes,
} from "lucide-react";

const ICON_MAP = {
  terminal: Terminal,
  download: Download,
  menu: Menu,
  dashboard: LayoutDashboard,
  folder_open: FolderOpen,
  memory: Cpu,
  sync: LoaderCircle,
  view_in_ar: Boxes,
  mail: Mail,
  github: Github,
  linkedin: Linkedin,
  location: MapPin,
  logout: LogOut,
  rocket_launch: Rocket,
  notifications: Bell,
  settings: Settings,
  trending_up: TrendingUp,
  add: Plus,
  search: Search,
  check_circle: CheckCircle2,
  archive: Archive,
  filter_list: Filter,
  sort: ArrowUpDown,
  public: Globe2,
  delete: Trash2,
  arrow_back: ArrowLeft,
  save: Save,
  edit_note: Edit3,
  code_blocks: FileCode2,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  image: Image,
  cloud_upload: CloudUpload,
  edit: Edit3,
  edit_square: SquarePen,
  upload_file: HardDriveUpload,
  visibility: Eye,
  visibility_off: EyeOff,
  drag_indicator: GripVertical,
  mark_email_read: MailCheck,
  warning: TriangleAlert,
  star: Star,
  article: FileText,
  perm_media: FileImage,
  code: Code2,
  work: BriefcaseBusiness,
  alternate_email: AtSign,
  javascript: FileCode2,
  database: DatabaseZap,
  cloud: Cloud,
  html: FileCode2,
  dns: Server,
  arrow_forward: ArrowRight,
  send: Send,
  rotate_right: RotateCw,
  zoom_in: ZoomIn,
  dark_mode: Moon,
  light_mode: Sun,
  deployed_code: FileCode2,
  content_copy: FileCode2,
  close: X,
  open_in_new: ExternalLink,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  lock: Lock,
  more_vert: MoreVertical,
  attach_file: Paperclip,
  description: FileText,
  analytics: TrendingUp,
  restart_alt: RotateCcw,
  build: Wrench,
  wallpaper: Braces,
  refresh: RefreshCw,
  css: Braces,
  check: CheckCircle2,
  sync_alt: RefreshCcw,
  person: UserCircle,
  message: MessageCircle,
};

export default function SymbolIcon({ name, className, strokeWidth = 2, ...props }) {
  const Icon = ICON_MAP[name] ?? Code2;
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
